name: SakuraLogin
main: com.moemc.login.Main
version: 1.2.0
author: KasuganoSora

commands:
  slogin:
    description: "§6§lSakura §b§lLogin§c§l 管理命令"
    usage: "§c§l[§6§lSakura §b§lLogin§c§l] §aby §dKasuganoSora §c/ §a查看帮助请输入 §6/slogin §bhelp"
    permission: "slogin.admin"
    permission-message: "§c§l[§6§lSakura §b§lLogin§c§l] §c您没有权限使用此命令，执行此命令需要权限 §eslogin.admin"